
/*addItens(); {
  const items = [
    {description: 'almofariz pestilo 120 ml porcelana', exist: true },
    {description: 'balão fundo chato  500 ml vidro', exist: true },
    {description: 'balão fundo chato 100 ml vidro', exist: true },
    {description: 'balão fundo chato 1000 ml vidro', exist: true },
    {description: 'balão fundo chato 200 ml vidro', exist: true },
    {description: 'balão fundo chato 25 ml vidro', exist: true },
    {description: 'balão fundo chato 250 ml vidro', exist: true },
    {description: 'balão fundo chato 50 ml vidro', exist: true },
    {description: 'balão fundo redondo 100 ml vidro', exist: true },
    {description: 'balão fundo redondo 1000 ml vidro', exist: true },
    {description: 'balão fundo redondo 250 ml vidro', exist: true },
    {description: 'balão fundo redondo 500 ml vidro', exist: true },
    {description: 'balão volumétrico 10 ml vidro', exist: true },
    {description: 'balão volumétrico 100 ml vidro', exist: true },
    {description: 'balão volumétrico 1000 ml vidro', exist: true },
    {description: 'balão volumétrico 200 ml vidro', exist: true },
    {description: 'balão volumétrico 25 ml vidro', exist: true },
    {description: 'balão volumétrico 250 ml vidro', exist: true },
    {description: 'balão volumétrico 5 ml vidro', exist: true },
    {description: 'balão volumétrico 50 ml vidro', exist: true },
    {description: 'balão volumétrico 500 ml vidro', exist: true },
    {description: 'bandeja grande plastico', exist: true },
    {description: 'bandeja média plastico', exist: true },
    {description: 'bandeja pequena plastico', exist: true },
    {description: 'barrilete  20 l', exist: true },
    {description: 'bastão 10x300 mm vidro', exist: true },
    {description: 'bastão 15x300 mm vidro', exist: true },
    {description: 'bastão 3x300 mm vidro', exist: true },
    {description: 'bastão 6x300 mm vidro', exist: true },
    {description: 'bastão 8x300 mm vidro', exist: true },
    {description: 'becker 100 ml polietileno', exist: true },
    {description: 'becker 100 ml vidro', exist: true },
    {description: 'becker 1000 ml polietileno', exist: true },
    {description: 'becker 1000 ml vidro', exist: true },
    {description: 'becker 150 ml vidro', exist: true },
    {description: 'becker 2000 ml polietileno', exist: true },
    {description: 'becker 250 ml polietileno', exist: true },
    {description: 'becker 250 ml vidro', exist: true },
    {description: 'becker 400 ml vidro', exist: true },
    {description: 'becker 50 ml polietileno', exist: true },
    {description: 'becker 50 ml vidro', exist: true },
    {description: 'becker 500 ml polietileno', exist: true },
    {description: 'becker 600 ml polietileno', exist: true },
    {description: 'becker 600 ml vidro', exist: true },
    {description: 'bico de bunsen', exist: true },
    {description: 'borbulhador 150 ml vidro', exist: true },
    {description: 'bureta valvula teflon 10 ml vidro', exist: true },
    {description: 'bureta valvula teflon 25 ml vidro', exist: true },
    {description: 'bureta valvula teflon 50 ml vidro', exist: true },
    {description: 'cadinho 100 ml porcelana', exist: true },
    {description: 'cadinho 20 ml porcelana', exist: true },
    {description: 'cadinho 35 ml porcelana', exist: true },
    {description: 'cadinho 40 ml porcelana', exist: true },
    {description: 'cadinho 50 ml porcelana', exist: true },
    {description: 'cálice 125 ml vidro', exist: true },
    {description: 'capsula 150 ml alumínio', exist: true },
    {description: 'capsula 25 ml porcelana', exist: true },
    {description: 'capsula 30 ml porcelana', exist: true },
    {description: 'capsula 50 ml porcelana', exist: true },
    {description: 'condensador tipo bolha vidro', exist: true },
    {description: 'condensador tipo expiral vidro', exist: true },
    {description: 'condensador tipo reto vidro', exist: true },
    {description: 'cone de inhoff 1000 ml vidro', exist: true },
    {description: 'erlenmeyer 100 ml vidro', exist: true },
    {description: 'erlenmeyer 1000 ml vidro', exist: true },
    {description: 'erlenmeyer 125 ml vidro', exist: true },
    {description: 'erlenmeyer 2000 ml vidro', exist: true },
    {description: 'erlenmeyer 250 ml vidro', exist: true },
    {description: 'erlenmeyer 50 ml vidro', exist: true },
    {description: 'erlenmeyer 500 ml vidro', exist: true },
    {description: 'escova para tubos média', exist: true },
    {description: 'escova para tubos pequena', exist: true },
    {description: 'espatula cabo de madeira grande', exist: true },
    {description: 'espatula cabo de madeira pequena', exist: true },
    {description: 'espatula média concava', exist: true },
    {description: 'espatula pequena concava', exist: true },
    {description: 'extrator soxhlet 250 ml vidro', exist: true },
    {description: 'filtro de proteção pra pêra', exist: true },
    {description: 'filtro de seringa com membrana de acetato de celulose', exist: true },
    {description: 'fita indicadora de ph', exist: true },
    {description: 'frasco 1000 ml polietileno', exist: true },
    {description: 'frasco 1000 ml vidro', exist: true },
    {description: 'frasco 125 ml p/ indicador vidro', exist: true },
    {description: 'frasco 250 ml vidro', exist: true },
    {description: 'frasco 400 ml vidro', exist: true },
    {description: 'frasco 500 ml vidro', exist: true },
    {description: 'frasco 800 ml vidro', exist: true },
    {description: 'frasco ambar 100 ml vidro', exist: true },
    {description: 'funil de buchner porcelana', exist: true },
    {description: 'funil de decantação 250 ml vidro', exist: true },
    {description: 'funil de decantação 500 ml vidro', exist: true },
    {description: 'funil de separação 250 ml vidro', exist: true },
    {description: 'funil de separação 500 ml vidro', exist: true },
    {description: 'funil de separação 60 ml vidro', exist: true },
    {description: 'funil de vidro grande vidro', exist: true },
    {description: 'funil de vidro médio vidro', exist: true },
    {description: 'funil de vidro pequeno vidro', exist: true },
    {description: 'funil plástico plastico', exist: true },
    {description: 'grau com pestilo porcelana', exist: true },
    {description: 'kit destilação arraste a vapor vidro', exist: true },
    {description: 'kit destilação fracionada vidro', exist: true },
    {description: 'kitassato 250 ml vidro', exist: true },
    {description: 'kitassato 500 ml vidro', exist: true },
    {description: 'macaco elevatório', exist: true },
    {description: 'membrana filtrante pacote 50', exist: true },
    {description: 'micropipeta 20 a 200 ul', exist: true },
    {description: 'micropipeta 200 a 1000 ul', exist: true },
    {description: 'micropipeta 2000 a 10000 ul', exist: true },
    {description: 'pêra automática', exist: true },
    {description: 'pêra verde', exist: true },
    {description: 'pêra vermelha', exist: true },
    {description: 'pinça com mufa para bureta', exist: true },
    {description: 'pinça p/ cadinho metal', exist: true },
    {description: 'pipeta graduada 1 ml vidro', exist: true },
    {description: 'pipeta graduada 10 ml vidro', exist: true },
    {description: 'pipeta graduada 25 ml vidro', exist: true },
    {description: 'pipeta graduada 3 ml vidro', exist: true },
    {description: 'pipeta graduada 5 ml vidro', exist: true },
    {description: 'pipeta volumétrica 1 ml vidro', exist: true },
    {description: 'pipeta volumétrica 10 ml vidro', exist: true },
    {description: 'pipeta volumétrica 100 ml vidro', exist: true },
    {description: 'pipeta volumétrica 15 ml vidro', exist: true },
    {description: 'pipeta volumétrica 2 ml vidro', exist: true },
    {description: 'pipeta volumétrica 20 ml vidro', exist: true },
    {description: 'pipeta volumétrica 25 ml vidro', exist: true },
    {description: 'pipeta volumétrica 5 ml vidro', exist: true },
    {description: 'pipeta volumétrica 50 ml vidro', exist: true },
    {description: 'pissete 250 ml polietileno', exist: true },
    {description: 'pissete 500 ml polietileno', exist: true },
    {description: 'placa cormatográfica caixa', exist: true },
    {description: 'placa de petri polietileno', exist: true },
    {description: 'placas de petri vidro', exist: true },
    {description: 'proveta graduada  50 ml vidro', exist: true },
    {description: 'proveta graduada  ml 5 ml vidro', exist: true },
    {description: 'proveta graduada 10 ml vidro', exist: true },
    {description: 'proveta graduada 100 ml c/ tampa vidro', exist: true },
    {description: 'proveta graduada 100 ml polietileno', exist: true },
    {description: 'proveta graduada 100 ml vidro', exist: true },
    {description: 'proveta graduada 1000 ml c/ tampa', exist: true },
    {description: 'proveta graduada 1000 ml polietileno', exist: true },
    {description: 'proveta graduada 1000 ml vidro', exist: true },
    {description: 'proveta graduada 1000 ml vidro', exist: true },
    {description: 'proveta graduada 25 ml polietileno', exist: true },
    {description: 'proveta graduada 250 ml polietileno', exist: true },
    {description: 'proveta graduada 5 ml vidro', exist: true },
    {description: 'proveta graduada 50 ml polietileno', exist: true },
    {description: 'proveta graduada 50 ml vidro', exist: true },
    {description: 'proveta graduada 500 ml polietileno', exist: true },
    {description: 'proveta graduada 500 ml vidro', exist: true },
    {description: 'proveta graduada c/ tampa 10 ml vidro', exist: true },
    {description: 'proveta graduada c/ tampa 50 ml vidro', exist: true },
    {description: 'seringa descartável 3 ml', exist: true },
    {description: 'suporte para laminas de vidro inox', exist: true },
    {description: 'suporte para pipetas', exist: true },
    {description: 'suporte universal', exist: true },
    {description: 'termometro mercúrio 130 °c vidro', exist: true },
    {description: 'tubo de ensaio 10x100 mm > vidro', exist: true },
    {description: 'vidro de relógio 150mm vidro', exist: true },
    {description: 'vidro de relógio 6mm vidro', exist: true }
  ];
}*/
